### ISSUE TITLE
Request: How can I set a specific number to display

### ISSUE THREAD

**Issue by oDresSystems** [amithkumarg/ionic-currency-input#8]
Hi, sorry to bother, just wondering how can I set a specific number en value, so the input can display a number different than 0, and when I type another number and navigate to other page and come back, the number I typed is there, like ngModel, could you helpme? thanks

**Comment by amithkumarg** [comment]
You can set the initial amount in the parent page/component:
`amount = 1234;`
And if you don't want to retain the user typed value in the page, you can reset it using Page/Component lifecycle hooks in angular.

**Comment by amithkumarg** [comment]
Seeing no response from OP, hence closing this issue.
